converter: wand -> pillow
inspirehep/plotextractor pull request #20
Opened 2017-07-07 13:53 UTC by kaplun

2017-07-07 13:54 UTC, kaplun commented
This is currently blocked by python-pillow/Pillow#2615

2017-07-07 13:55 UTC, kaplun commented on plotextractor/converter.py
> +                raise
This is a leftover, to make explicit the ghostscript error.

2025-04-30 06:20 UTC, drjova requested changes
Thanks @DonHaul few comments, also could we test it with existing workflows and see if they produce same results?

2025-04-30 06:20 UTC, drjova commented on .github/workflows/test-python-2.yml
> +        run: sudo apt-get update -y && sudo apt-get install -y ghostscript poppler-utils python2
this dep needs to be part of next as well

2025-04-30 06:20 UTC, drjova commented on plotextractor/converter.py
> +            except (KeyError, IOError, Image.DecompressionBombError) as e:
What about pdf2image errors?

2025-04-30 07:08 UTC, ioannistsanaktsidis requested changes

2025-04-30 07:08 UTC, ioannistsanaktsidis commented on setup.py
> +    'Wand>=0.4.1,<=0.5.9',
This can be removed no ?

2025-04-30 07:08 UTC, ioannistsanaktsidis commented on plotextractor/converter.py
> +            return True
Shouldn't we return outside the with block ?

2025-04-30 07:31 UTC, DonHaul commented on .github/workflows/test-python-2.yml
> +        run: sudo apt-get update -y && sudo apt-get install -y ghostscript poppler-utils python2
it is already https://github.com/inspirehep/inspire-next/blob/master/Dockerfile#L44

2025-05-02 14:23 UTC, DonHaul commented
Based on my investigation. if, when reading a pdf that is very big e.g.3.2MB, the `pdf2ppm` uses to much memory, this subprocess gets killed returning 0 results.

2025-05-02 14:53 UTC, DonHaul commented
Because we are using `python2.7` we can only use pdf2img 1.7.1 which does not allow us to simply convert from `pdf` to `png` without loading the object in memory into a `PIL.Image`, this feature was added in `1.10`. due to this we have to first load image into memory, and then save it in a later step.
With https://github.com/Belval/pdf2image/releases/tag/v1.10.0 we can skip these 2 last steps

This is only important for very highresolution pdfs that get converted into very large images (lots of pixels) that will then occupy lots of space in memory.


An alternative would be to use `pdf2ppm` directly. 
A command such as
```
pdftoppm -png -r 200 -singlefile "tests/data/eada5d4d-efb3-4e89-9049-84c3e0849922.pdf" "tests/data/eada5d4d-efb3-4e89-9049-84c3e0849922"
```
would replace
```
 imgs = convert_from_path(from_file)
        if len(imgs):
            imgs[0].save(to_file, image_format)
```

2025-05-05 11:39 UTC, ioannistsanaktsidis reviewed
In overall,  I think it looks good. What do you think guys?  Should we give it a try? 

@DonHaul did you manage to test it with all the different types we are using? 

@drjova could you give it another review from your side?

2025-05-05 11:39 UTC, ioannistsanaktsidis commented on plotextractor/converter.py
> +Image.MAX_IMAGE_PIXELS = 150000000
What do you think about this one guys? We are setting it to 150 million pixels. Should we allow this kind of sizes? 

cc @drjova

2025-05-05 11:39 UTC, ioannistsanaktsidis commented on tests/data/eada5d4d-efb3-4e89-9049-84c3e0849922.png.png
Do we need this? isn't it hte same as the one above ?

2025-05-05 11:44 UTC, DonHaul commented on tests/data/eada5d4d-efb3-4e89-9049-84c3e0849922.png.png
arefacts from testing. deleted

2025-05-05 12:56 UTC, DonHaul commented on plotextractor/converter.py
> +Image.MAX_IMAGE_PIXELS = 150000000
in the end its not required to set this setting as it mainly used to allow very high quality pdfs to be loaded into memory via `pillow`. Since pdfppm is able to convert from `pdf` to `png` without loading the image in memory, this setting does not come to into play

2025-05-05 14:25 UTC, drjova approved these changes

2025-05-05 14:30 UTC, ioannistsanaktsidis approved these changes
LGTM ! Good job 🎉

2025-05-05 16:03 UTC, merged